// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSZuriSuzNnFrMGzz255NW7wrmuGEwtTI',
    appId: '1:420721807194:web:e9bfdd9ce35b78808a6d63',
    messagingSenderId: '420721807194',
    projectId: 'emart-53097',
    authDomain: 'emart-53097.firebaseapp.com',
    storageBucket: 'emart-53097.appspot.com',
    measurementId: 'G-PCS71VM3G5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz7NgjiQDZVLvtVWtjN33yWyR8h0zodhU',
    appId: '1:420721807194:android:44d1bd65f5477d3c8a6d63',
    messagingSenderId: '420721807194',
    projectId: 'emart-53097',
    storageBucket: 'emart-53097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOmI_dKwKOjiBWGMlHy_o46xHNSovxKto',
    appId: '1:420721807194:ios:25fdf8b5c98476d18a6d63',
    messagingSenderId: '420721807194',
    projectId: 'emart-53097',
    storageBucket: 'emart-53097.appspot.com',
    iosBundleId: 'com.example.eMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOmI_dKwKOjiBWGMlHy_o46xHNSovxKto',
    appId: '1:420721807194:ios:25fdf8b5c98476d18a6d63',
    messagingSenderId: '420721807194',
    projectId: 'emart-53097',
    storageBucket: 'emart-53097.appspot.com',
    iosBundleId: 'com.example.eMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSZuriSuzNnFrMGzz255NW7wrmuGEwtTI',
    appId: '1:420721807194:web:92a8a8603c4d3e918a6d63',
    messagingSenderId: '420721807194',
    projectId: 'emart-53097',
    authDomain: 'emart-53097.firebaseapp.com',
    storageBucket: 'emart-53097.appspot.com',
    measurementId: 'G-P6HFH2X6QF',
  );
}
